// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	greet: (name: string) => __TAURI_INVOKE<string>("greet", { name }),
	appDir: () => typedError<string, string>(__TAURI_INVOKE("app_dir")),
	/**  是否通过应用商店类渠道安装（内置更新应关闭）。具体判断在 `utils/app_store.rs`。 */
	isAppStore: () => __TAURI_INVOKE<boolean>("is_app_store"),
	/**  更新安装完成后重启。macOS 上延迟 `open` 再退出，避免 single-instance 与 `relaunch()` 竞态。 */
	restartAfterUpdate: () => typedError<null, string>(__TAURI_INVOKE("restart_after_update")),
	testConn: (conf: ConnConfig) => typedError<null, string>(__TAURI_INVOKE("test_conn", { conf })),
	masters: (conf: ConnConfig) => typedError<{ [key in string]: string }[], string>(__TAURI_INVOKE("masters", { conf })),
	connList: (connList: ConnConfig[]) => typedError<null, string>(__TAURI_INVOKE("conn_list", { connList })),
	appSettings: (appSettings: AppSettings) => typedError<null, string>(__TAURI_INVOKE("app_settings", { appSettings })),
	connect: (id: string) => typedError<ServerCapabilities, string>(__TAURI_INVOKE("connect", { id })),
	disconnect: (id: string) => typedError<null, string>(__TAURI_INVOKE("disconnect", { id })),
	dbList: (id: string) => typedError<RedisDB[], string>(__TAURI_INVOKE("db_list", { id })),
	selectDb: (id: string, db: number) => typedError<null, string>(__TAURI_INVOKE("select_db", { id, db })),
	info: (id: string, node: string | null) => typedError<RedisInfo, string>(__TAURI_INVOKE("info", { id, node })),
	infoList: (id: string) => typedError<RedisInfo[], string>(__TAURI_INVOKE("info_list", { id })),
	chart: (id: string, node: string | null) => typedError<RedisChart, string>(__TAURI_INVOKE("chart", { id, node })),
	chartList: (id: string) => typedError<RedisChart[], string>(__TAURI_INVOKE("chart_list", { id })),
	nodeList: (id: string) => typedError<RedisNode[], string>(__TAURI_INVOKE("node_list", { id })),
	scan: (id: string, param: ScanParam) => typedError<ScanResult_Serialize, string>(__TAURI_INVOKE("scan", { id, param })),
	fieldScan: (id: string, param: FieldScanParam_Deserialize) => typedError<FieldScanResult, string>(__TAURI_INVOKE("field_scan", { id, param })),
	ttl: (id: string, key: RedisKey_Deserialize, ttl: number) => typedError<null, string>(__TAURI_INVOKE("ttl", { id, key, ttl })),
	set: (id: string, param: RedisSetParam_Deserialize) => typedError<null, string>(__TAURI_INVOKE("set", { id, param })),
	del: (id: string, key: RedisKey_Deserialize) => typedError<null, string>(__TAURI_INVOKE("del", { id, key })),
	rename: (id: string, key: RedisKey_Deserialize, newKey: RedisKey_Deserialize) => typedError<RedisKey_Serialize, string>(__TAURI_INVOKE("rename", { id, key, newKey })),
	copy: (id: string, param: RedisCopyParam_Deserialize) => typedError<RedisKey_Serialize, string>(__TAURI_INVOKE("copy", { id, param })),
	fieldAdd: (id: string, param: RedisFieldAdd_Deserialize) => typedError<RedisKey_Serialize, string>(__TAURI_INVOKE("field_add", { id, param })),
	fieldSet: (id: string, param: RedisFieldSet_Deserialize) => typedError<null, string>(__TAURI_INVOKE("field_set", { id, param })),
	fieldGet: (id: string, param: RedisFieldGet_Deserialize) => typedError<RedisFieldValue, string>(__TAURI_INVOKE("field_get", { id, param })),
	hashKeys: (id: string, param: RedisHashKeys_Deserialize) => typedError<string[], string>(__TAURI_INVOKE("hash_keys", { id, param })),
	hashValues: (id: string, param: RedisHashKeys_Deserialize) => typedError<string[], string>(__TAURI_INVOKE("hash_values", { id, param })),
	fieldPop: (id: string, param: RedisPop_Deserialize) => typedError<string, string>(__TAURI_INVOKE("field_pop", { id, param })),
	fieldDel: (id: string, param: RedisFieldDel_Deserialize) => typedError<null, string>(__TAURI_INVOKE("field_del", { id, param })),
	zsetRank: (id: string, param: RedisZsetRank_Deserialize) => typedError<RedisZsetRankResult, string>(__TAURI_INVOKE("zset_rank", { id, param })),
	zsetRange: (id: string, param: RedisZsetRange_Deserialize) => typedError<RedisZsetRangeItem[], string>(__TAURI_INVOKE("zset_range", { id, param })),
	objectInfo: (id: string, key: RedisKey_Deserialize) => typedError<RedisObjectInfo, string>(__TAURI_INVOKE("object_info", { id, key })),
	executeCommand: (id: string, param: RedisCommand) => typedError<string, string>(__TAURI_INVOKE("execute_command", { id, param })),
	aclUsers: (id: string) => typedError<string[], string>(__TAURI_INVOKE("acl_users", { id })),
	aclListUsers: (id: string) => typedError<AclUserDetail[], string>(__TAURI_INVOKE("acl_list_users", { id })),
	aclGetuser: (id: string, username: string) => typedError<AclUserDetail, string>(__TAURI_INVOKE("acl_getuser", { id, username })),
	aclSetuser: (id: string, param: AclSetuserParam) => typedError<null, string>(__TAURI_INVOKE("acl_setuser", { id, param })),
	aclDeluser: (id: string, usernames: string[]) => typedError<number, string>(__TAURI_INVOKE("acl_deluser", { id, usernames })),
	aclWhoami: (id: string) => typedError<string, string>(__TAURI_INVOKE("acl_whoami", { id })),
	aclCat: (id: string, category: string | null) => typedError<string[], string>(__TAURI_INVOKE("acl_cat", { id, category })),
	aclGenpass: (id: string, bits: number | null) => typedError<string, string>(__TAURI_INVOKE("acl_genpass", { id, bits })),
	aclSave: (id: string) => typedError<null, string>(__TAURI_INVOKE("acl_save", { id })),
	aclLoad: (id: string) => typedError<null, string>(__TAURI_INVOKE("acl_load", { id })),
	aclLog: (id: string, count: number | null) => typedError<AclLogEntry[], string>(__TAURI_INVOKE("acl_log", { id, count })),
	aclLogReset: (id: string) => typedError<null, string>(__TAURI_INVOKE("acl_log_reset", { id })),
	aclDryrun: (id: string, username: string, command: string) => typedError<string, string>(__TAURI_INVOKE("acl_dryrun", { id, username, command })),
	slowLog: (id: string, count: number | null, node: string | null) => typedError<RedisSlowLog[], string>(__TAURI_INVOKE("slow_log", { id, count, node })),
	memoryUsage: (id: string, param: RedisMemoryParam) => typedError<RedisKeySize_Serialize[], string>(__TAURI_INVOKE("memory_usage", { id, param })),
	configGet: (id: string, pattern: string, node: string | null) => typedError<{ [key in string]: string }, string>(__TAURI_INVOKE("config_get", { id, pattern, node })),
	configSet: (id: string, key: string, value: string, node: string | null) => typedError<null, string>(__TAURI_INVOKE("config_set", { id, key, value, node })),
	clientList: (id: string, node: string | null, clientType: string | null) => typedError<RedisClientInfo[], string>(__TAURI_INVOKE("client_list", { id, node, clientType })),
	publish: (id: string, channel: string, message: string, msgFmt: "utf8" | "base64" | null) => typedError<null, string>(__TAURI_INVOKE("publish", { id, channel, message, msgFmt })),
	subscribe: (id: string, channel: string | null) => typedError<null, string>(__TAURI_INVOKE("subscribe", { id, channel })),
	subscribeStop: (id: string) => typedError<null, string>(__TAURI_INVOKE("subscribe_stop", { id })),
	monitor: (id: string, node: string) => typedError<null, string>(__TAURI_INVOKE("monitor", { id, node })),
	monitorStop: (id: string) => typedError<null, string>(__TAURI_INVOKE("monitor_stop", { id })),
	batchDel: (id: string, param: RedisBatchKey_Deserialize) => typedError<null, string>(__TAURI_INVOKE("batch_del", { id, param })),
	batchTtl: (id: string, param: RedisBatchTtl_Deserialize) => typedError<null, string>(__TAURI_INVOKE("batch_ttl", { id, param })),
	exportCsv: (id: string, param: RedisExportCsv_Deserialize) => typedError<null, string>(__TAURI_INVOKE("export_csv", { id, param })),
	importCsv: (id: string, param: RedisImportCsv) => typedError<null, string>(__TAURI_INVOKE("import_csv", { id, param })),
	importCmd: (id: string, file: string) => typedError<null, string>(__TAURI_INVOKE("import_cmd", { id, file })),
	mockData: (id: string, count: number) => typedError<null, string>(__TAURI_INVOKE("mock_data", { id, count })),
	keyType: (id: string, key: RedisKey_Deserialize) => typedError<string, string>(__TAURI_INVOKE("key_type", { id, key })),
	getKeyAsCommand: (id: string, key: RedisKey_Deserialize) => typedError<string, string>(__TAURI_INVOKE("get_key_as_command", { id, key })),
	getFieldAsCommand: (id: string, param: RedisFieldAsCommand_Deserialize) => typedError<string, string>(__TAURI_INVOKE("get_field_as_command", { id, param })),
	xinfoGroups: (id: string, key: RedisKey_Deserialize) => typedError<XInfoGroup[], string>(__TAURI_INVOKE("xinfo_groups", { id, key })),
	xinfoConsumers: (id: string, key: RedisKey_Deserialize, group: string) => typedError<XInfoConsumer[], string>(__TAURI_INVOKE("xinfo_consumers", { id, key, group })),
	keySlot: (id: string, key: RedisKey_Deserialize) => typedError<number, string>(__TAURI_INVOKE("key_slot", { id, key })),
	keyNode: (id: string, key: RedisKey_Deserialize) => typedError<RedisNode[], string>(__TAURI_INVOKE("key_node", { id, key })),
	flushDb: (id: string) => typedError<null, string>(__TAURI_INVOKE("flush_db", { id })),
	flushAll: (id: string) => typedError<null, string>(__TAURI_INVOKE("flush_all", { id })),
	commandLogs: (id: string, limit: number | null) => typedError<CommandLogEntry[], string>(__TAURI_INVOKE("command_logs", { id, limit })),
	commandLogsClear: (id: string) => typedError<null, string>(__TAURI_INVOKE("command_logs_clear", { id })),
};

/* Types */
export type AclLogEntry = {
	count: number,
	reason: string,
	context: string,
	object: string,
	username: string,
	ageSeconds: number | null,
	clientInfo: string,
	entryId: number,
	timestampCreated: number,
	timestampLastUpdated: number,
};

export type AclSetuserParam = {
	username: string,
	enabled: boolean,
	passwordHashes: string[],
	commandRules: string[],
	keyPatterns: string[],
	channelPatterns: string[],
	/**  Redis 7.2+ selector，每条为 SETUSER 括号内规则串（如 `-@all +set ~key2`） */
	selectors: string[],
};

export type AclUserDetail = {
	username: string,
	enabled: boolean,
	nopass: boolean,
	flags: string[],
	passwordHashes: string[],
	commandRules: string[],
	keyPatterns: string[],
	channelPatterns: string[],
	selectors: string[],
};

export type AppSettings = {
	commandTimeoutSecs: number,
};

/**  前后端 IPC 字节格式：utf8 文本或 base64 原始字节（hex/binary/msgpack 等视图格式在前端处理） */
export type BytesFormat = "utf8" | "base64";

/**  终端输出格式，对应 redis-cli `--raw` / `--csv` / `--json`；默认 TTY */
export type CliOutputMode = "standard" | "raw" | "json" | "csv";

export type CommandLogEntry = {
	id: number,
	timestamp: string,
	dbIndex: number,
	command: string,
	args: string[],
	fullCommand: string,
	durationMs: number,
	error: string | null,
};

export type ConnConfig = {
	id: string,
	name: string,
	host: string,
	port: number,
	username: string,
	password: string,
	db: number,
	cluster: boolean,
	ssl: boolean,
	sslOption: SslOption,
	sentinel: boolean,
	sentinelOption: SentinelOption,
	ssh: boolean,
	sshOption: SshOption,
	meta?: { [key in string]: ConnMetaValue },
};

/**  连接 meta 值（与前端 JSON 结构一致，供 specta 导出） */
export type ConnMetaValue = string | number | null | boolean | { [key in string]: ConnMetaValue } | ConnMetaValue[] | "Null";

export type FieldScanParam = FieldScanParam_Serialize | FieldScanParam_Deserialize;

export type FieldScanParam_Deserialize = {
	key: RedisKey_Deserialize,
	count: number,
	cursor: ScanCursor | null,
	/**  HSCAN/SSCAN/ZSCAN 的 MATCH pattern（前端字段名 match） */
	match: string,
	/**  完全匹配：true 时走 HGET / SISMEMBER / ZSCORE */
	exact: boolean,
	meta: FiledScanMeta | null,
	bytesFormat: BytesFormat | null,
	/**  是否拉取 TYPE/TTL/MEMORY/HLEN；前端续扫时为 false */
	includeMeta: boolean | null,
	/**  续扫时传入（include_meta=false），避免重复 TYPE */
	keyType: string | null,
	/**  Hash 扫描是否附带 HTTL（默认 false 以提速） */
	includeFieldTtl: boolean | null,
};

export type FieldScanParam_Serialize = {
	key: RedisKey_Serialize,
	count: number,
	cursor: ScanCursor | null,
	/**  HSCAN/SSCAN/ZSCAN 的 MATCH pattern（前端字段名 match） */
	match: string,
	/**  完全匹配：true 时走 HGET / SISMEMBER / ZSCORE */
	exact: boolean,
	meta: FiledScanMeta | null,
	bytesFormat: BytesFormat | null,
	/**  是否拉取 TYPE/TTL/MEMORY/HLEN；前端续扫时为 false */
	includeMeta: boolean | null,
	/**  续扫时传入（include_meta=false），避免重复 TYPE */
	keyType: string | null,
	/**  Hash 扫描是否附带 HTTL（默认 false 以提速） */
	includeFieldTtl: boolean | null,
};

export type FieldScanResult = {
	type: string,
	ttl: number,
	size: number,
	value: any,
	cursor: ScanCursor,
	length: number,
	/**  STRING 因超过 value_byte_limit 仅返回预览片段时为 true */
	valueTruncated: boolean,
};

export type FiledScanMeta = {
	/**  Stream XREVRANGE 上界和下界 */
	maxId: string,
	minId: string,
	/**  STRING 全量加载字节上限；超过且未 force 时仅 GETRANGE 预览前 value_preview_bytes */
	valueByteLimit: number | null,
	valuePreviewBytes: number | null,
	forceFullValue: boolean | null,
	/**  List LRANGE 下界；空则 0 */
	listMinIndex: number | null,
	/**  List LRANGE 上界；空则 len-1 */
	listMaxIndex: number | null,
	/**  List 扫描方向：true 从 max 向 min，false 从 min 向 max */
	listDesc: boolean | null,
	/**  Stream 扫描方向：true 从 max 向 min（XREVRANGE），false 从 min 向 max（XRANGE） */
	streamDesc: boolean | null,
};

export type RedisBatchKey = RedisBatchKey_Serialize | RedisBatchKey_Deserialize;

export type RedisBatchKey_Deserialize = {
	match: string,
	keyList: RedisKey_Deserialize[],
};

export type RedisBatchKey_Serialize = {
	match: string,
	keyList: RedisKey_Serialize[],
};

export type RedisBatchTtl = RedisBatchTtl_Serialize | RedisBatchTtl_Deserialize;

export type RedisBatchTtl_Deserialize = {
	keyList: RedisKey_Deserialize[],
	ttl: number,
};

export type RedisBatchTtl_Serialize = {
	keyList: RedisKey_Serialize[],
	ttl: number,
};

export type RedisChart = {
	node: string,
	keyTotal: number,
	connectedClients: number,
	instantaneousOpsPerSec: number | null,
	usedMemory: number,
	instantaneousInputKbps: number | null,
	instantaneousOutputKbps: number | null,
	totalConnectionsReceived: number,
	totalCommandsProcessed: number,
	keyspaceHits: number,
	keyspaceMisses: number,
	cacheHitRatio: number | null,
};

export type RedisClientInfo = {
	id?: number,
	addr?: string,
	laddr?: string,
	fd?: number,
	name?: string,
	age?: number,
	idle?: number,
	flags?: string,
	db?: number,
	sub?: number,
	psub?: number,
	ssub?: number,
	multi?: number,
	watch?: number,
	qbuf?: number,
	qbufFree?: number,
	argvMem?: number,
	multiMem?: number,
	obl?: number,
	oll?: number,
	omem?: number,
	totMem?: number,
	events?: string,
	cmd?: string,
	user?: string,
	redir?: number,
	resp?: number,
	rbp?: number,
	rbs?: number,
	ioThread?: number,
};

export type RedisCommand = {
	command: string,
	node: string | null,
	autoBroadcast: boolean | null,
	/**  终端输出格式；`None` 等同 `standard`（TTY） */
	outputMode: CliOutputMode | null,
};

export type RedisCopyParam = RedisCopyParam_Serialize | RedisCopyParam_Deserialize;

export type RedisCopyParam_Deserialize = {
	source: RedisKey_Deserialize,
	destination: RedisKey_Deserialize,
	db: number,
};

export type RedisCopyParam_Serialize = {
	source: RedisKey_Serialize,
	destination: RedisKey_Serialize,
	db: number,
};

export type RedisDB = {
	db: number,
	size: number,
};

export type RedisExportCsv = RedisExportCsv_Serialize | RedisExportCsv_Deserialize;

export type RedisExportCsv_Deserialize = {
	match: string,
	keyList: RedisKey_Deserialize[],
	file: string,
	withTtl: boolean,
	exportFormat?: string,
};

export type RedisExportCsv_Serialize = {
	match: string,
	keyList: RedisKey_Serialize[],
	file: string,
	withTtl: boolean,
	exportFormat: string,
};

export type RedisFieldAdd = RedisFieldAdd_Serialize | RedisFieldAdd_Deserialize;

export type RedisFieldAdd_Deserialize = {
	/**  目标 Redis 键（与 `RedisFieldSet` / `RedisFieldDel` 一致）；`bytes` 为空时由 `key` 文本 + `key_fmt` 解析 */
	key: RedisKey_Deserialize,
	mode: string,
	type: string,
	ttl: number,
	value: string,
	listPushMethod: string,
	fieldValueList: RedisFieldValue[],
	streamId: string,
	/**  仅 Redis 顶层键名（`key`）如何解码为字节；不含 Hash/Stream 的字段名 */
	keyFmt: BytesFormat | null,
	/**  除 Redis 键名外的输入：String 值、Hash 字段名与值、List/Set/ZSet 成员、Stream 字段名与值等 */
	valFmt: BytesFormat | null,
};

export type RedisFieldAdd_Serialize = {
	/**  目标 Redis 键（与 `RedisFieldSet` / `RedisFieldDel` 一致）；`bytes` 为空时由 `key` 文本 + `key_fmt` 解析 */
	key: RedisKey_Serialize,
	mode: string,
	type: string,
	ttl: number,
	value: string,
	listPushMethod: string,
	fieldValueList: RedisFieldValue[],
	streamId: string,
	/**  仅 Redis 顶层键名（`key`）如何解码为字节；不含 Hash/Stream 的字段名 */
	keyFmt: BytesFormat | null,
	/**  除 Redis 键名外的输入：String 值、Hash 字段名与值、List/Set/ZSet 成员、Stream 字段名与值等 */
	valFmt: BytesFormat | null,
};

export type RedisFieldAsCommand = RedisFieldAsCommand_Serialize | RedisFieldAsCommand_Deserialize;

export type RedisFieldAsCommand_Deserialize = {
	key: RedisKey_Deserialize,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	streamId: string,
	valFmt: BytesFormat | null,
};

export type RedisFieldAsCommand_Serialize = {
	key: RedisKey_Serialize,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	streamId: string,
	valFmt: BytesFormat | null,
};

export type RedisFieldDel = RedisFieldDel_Serialize | RedisFieldDel_Deserialize;

export type RedisFieldDel_Deserialize = {
	key: RedisKey_Deserialize,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	streamId: string,
	valFmt: BytesFormat | null,
};

export type RedisFieldDel_Serialize = {
	key: RedisKey_Serialize,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	streamId: string,
	valFmt: BytesFormat | null,
};

export type RedisFieldGet = RedisFieldGet_Serialize | RedisFieldGet_Deserialize;

export type RedisFieldGet_Deserialize = {
	key: RedisKey_Deserialize,
	fieldIndex: number,
	fieldKey: string,
	/**  ZSet 成员定位；Hash 用 field_key、List 用 field_index */
	fieldValue: string,
	/**  为 true 时对 Hash 执行 HTTL；默认 false */
	includeFieldTtl: boolean | null,
	valFmt: BytesFormat | null,
};

export type RedisFieldGet_Serialize = {
	key: RedisKey_Serialize,
	fieldIndex: number,
	fieldKey: string,
	/**  ZSet 成员定位；Hash 用 field_key、List 用 field_index */
	fieldValue: string,
	/**  为 true 时对 Hash 执行 HTTL；默认 false */
	includeFieldTtl: boolean | null,
	valFmt: BytesFormat | null,
};

export type RedisFieldSet = RedisFieldSet_Serialize | RedisFieldSet_Deserialize;

export type RedisFieldSet_Deserialize = {
	key: RedisKey_Deserialize,
	srcFieldValue: string,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	fieldScore: number | null,
	fieldTtl: number,
	/**  true：界面展示/编辑字段 TTL；false：不拉取列表 TTL，保存时仍保留原有过期 */
	includeFieldTtl: boolean | null,
	/**  编辑字段时解析用户输入（含 Hash 字段名）；Redis 键由 `key` 承载，不再经此格式解析 */
	valFmt: BytesFormat | null,
};

export type RedisFieldSet_Serialize = {
	key: RedisKey_Serialize,
	srcFieldValue: string,
	fieldIndex: number,
	fieldKey: string,
	fieldValue: string,
	fieldScore: number | null,
	fieldTtl: number,
	/**  true：界面展示/编辑字段 TTL；false：不拉取列表 TTL，保存时仍保留原有过期 */
	includeFieldTtl: boolean | null,
	/**  编辑字段时解析用户输入（含 Hash 字段名）；Redis 键由 `key` 承载，不再经此格式解析 */
	valFmt: BytesFormat | null,
};

export type RedisFieldValue = {
	fieldKey: string,
	fieldValue: string,
	fieldScore: number | null,
	fieldTtl: number,
};

export type RedisHashKeys = RedisHashKeys_Serialize | RedisHashKeys_Deserialize;

export type RedisHashKeys_Deserialize = {
	key: RedisKey_Deserialize,
	/**  Hash 字段名/值解码格式，与 field_get / fieldScan 一致 */
	valFmt: BytesFormat | null,
};

export type RedisHashKeys_Serialize = {
	key: RedisKey_Serialize,
	/**  Hash 字段名/值解码格式，与 field_get / fieldScan 一致 */
	valFmt: BytesFormat | null,
};

export type RedisImportCsv = {
	file: string,
	ttl: number,
	handleTtl: string,
	handleConflict: string,
};

export type RedisInfo = {
	node: string,
	info: string,
};

export type RedisKey = RedisKey_Serialize | RedisKey_Deserialize;

export type RedisKeySize = RedisKeySize_Serialize | RedisKeySize_Deserialize;

export type RedisKeySize_Deserialize = {
	key: string,
	bytes: string,
	type: string,
	size: number,
};

export type RedisKeySize_Serialize = {
	key: string,
	bytes: string,
	type: string,
	size: number,
};

export type RedisKey_Deserialize = {
	key: string,
	bytes: string,
};

export type RedisKey_Serialize = {
	key: string,
	bytes: string,
};

export type RedisMemoryParam = {
	match: string | null,
	sizeLimit: number,
	countLimit: number,
	scanCount: number,
	scanTotal: number,
	sleepMillis: number,
	needKeyType: boolean | null,
};

export type RedisNode = {
	id: string,
	node: string,
	flags: string,
	slots: string | null,
	slaveOfNode: string | null,
};

export type RedisObjectInfo = {
	encoding: string | null,
	idleTime: number | null,
	/**  IDLETIME 因 maxmemory-policy 等不可用时的错误信息 */
	idleTimeError: string | null,
	refcount: number | null,
	freq: number | null,
	/**  FREQ 因 maxmemory-policy 等不可用时的错误信息 */
	freqError: string | null,
};

export type RedisPop = RedisPop_Serialize | RedisPop_Deserialize;

export type RedisPop_Deserialize = {
	key: RedisKey_Deserialize,
	/**  操作模式（LPOP/RPOP/SPOP/ZPOPMIN/ZPOPMAX） */
	mode: string,
	/**  弹出元素的展示格式 */
	valFmt: BytesFormat | null,
};

export type RedisPop_Serialize = {
	key: RedisKey_Serialize,
	/**  操作模式（LPOP/RPOP/SPOP/ZPOPMIN/ZPOPMAX） */
	mode: string,
	/**  弹出元素的展示格式 */
	valFmt: BytesFormat | null,
};

export type RedisSetParam = RedisSetParam_Serialize | RedisSetParam_Deserialize;

export type RedisSetParam_Deserialize = {
	key: RedisKey_Deserialize,
	value: string,
	ttl: number,
	keyType: string | null,
	inputFormat: BytesFormat | null,
};

export type RedisSetParam_Serialize = {
	key: RedisKey_Serialize,
	value: string,
	ttl: number,
	keyType: string | null,
	inputFormat: BytesFormat | null,
};

export type RedisSlowLog = {
	node: string,
	id: number,
	time: string,
	client: string,
	command: string,
	cost: number | null,
	clientName: string,
};

export type RedisZsetRange = RedisZsetRange_Serialize | RedisZsetRange_Deserialize;

export type RedisZsetRangeItem = {
	value: string,
	score: number | null,
};

export type RedisZsetRange_Deserialize = {
	key: RedisKey_Deserialize,
	/**  true: ZREVRANGE (分数从高到低); false: ZRANGE (分数从低到高) */
	reverse: boolean,
	/**  返回数量限制 */
	count: number,
	/**  值解码格式 */
	valFmt: BytesFormat | null,
};

export type RedisZsetRange_Serialize = {
	key: RedisKey_Serialize,
	/**  true: ZREVRANGE (分数从高到低); false: ZRANGE (分数从低到高) */
	reverse: boolean,
	/**  返回数量限制 */
	count: number,
	/**  值解码格式 */
	valFmt: BytesFormat | null,
};

export type RedisZsetRank = RedisZsetRank_Serialize | RedisZsetRank_Deserialize;

export type RedisZsetRankResult = {
	rank: number | null,
	revRank: number | null,
};

export type RedisZsetRank_Deserialize = {
	key: RedisKey_Deserialize,
	member: string,
	valFmt: BytesFormat | null,
};

export type RedisZsetRank_Serialize = {
	key: RedisKey_Serialize,
	member: string,
	valFmt: BytesFormat | null,
};

export type ScanCursor = {
	readyNodes: string[],
	nowNode: string,
	nowCursor: number,
	streamCursor: string,
	finished: boolean,
};

export type ScanParam = {
	match: string,
	type: string | null,
	cursor: ScanCursor | null,
	/**  完全匹配：true 时后端 EXISTS；false 时 SCAN */
	exact: boolean,
};

export type ScanResult = ScanResult_Serialize | ScanResult_Deserialize;

export type ScanResult_Deserialize = {
	keyList: RedisKey_Deserialize[],
	cursor: ScanCursor,
};

export type ScanResult_Serialize = {
	keyList: RedisKey_Serialize[],
	cursor: ScanCursor,
};

export type SentinelOption = {
	masterName: string,
	masterUsername: string,
	masterPassword: string,
};

export type ServerCapabilities = {
	version: string,
	isValkey: boolean,
	infoSupported: boolean,
	aclSupported: boolean,
	aclDryrunSupported: boolean,
	aclSelectorSupported: boolean,
	httlSupported: boolean,
	/**  集群模式是否支持编号数据库（Valkey 9+） */
	clusterDbSupported: boolean,
};

export type SshOption = {
	host: string,
	port: number,
	loginType: string,
	username: string,
	password: string,
	pkfile: string,
	passphrase: string,
};

export type SslOption = {
	key: string,
	cert: string,
	ca: string,
};

export type XInfoConsumer = {
	name: string,
	pending: number,
	idle: number,
};

export type XInfoGroup = {
	name: string,
	consumers: number,
	pending: number,
	lastDeliveredId: string,
	entriesRead: number | null,
	lag: number | null,
};

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

